[package]
name = "cli_chess"
version = "0.1.0"
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2018"

[dependencies]
pretty_env_logger = "0.4.0"
log = "0.4.8"
console = "0.11.3"
serde = "1.0.114"

[dev-dependencies]
rstest = "0.6.4"
insta = "0.16.1"
